#ifndef BTSTACK_CONFIG_H
#define BTSTACK_CONFIG_H

// BTstack configuration for Pico W
#define ENABLE_BLE
#define ENABLE_LE_PERIPHERAL
#define ENABLE_LE_CENTRAL
#define ENABLE_L2CAP_LE_CREDIT_BASED_FLOW_CONTROL_MODE
#define ENABLE_LE_DATA_LENGTH_EXTENSION
#define ENABLE_LE_EXTENDED_ADVERTISING
#define ENABLE_LE_PERIODIC_ADVERTISING

// Memory configuration
#define MAX_ATT_DB_SIZE 512
#define MAX_NR_GATT_CLIENTS 1
#define MAX_NR_HCI_CONNECTIONS 1
#define MAX_NR_L2CAP_SERVICES 2
#define MAX_NR_L2CAP_CHANNELS 2
#define MAX_NR_RFCOMM_MULTIPLEXERS 0
#define MAX_NR_RFCOMM_SERVICES 0
#define MAX_NR_RFCOMM_CHANNELS 0
#define MAX_NR_BTSTACK_LINK_KEY_DB_MEMORY_ENTRIES 0
#define MAX_NR_BNEP_SERVICES 0
#define MAX_NR_BNEP_CHANNELS 0
#define MAX_NR_HFP_CONNECTIONS 0
#define MAX_NR_WHITELIST_ENTRIES 1
#define MAX_NR_SM_LOOKUP_ENTRIES 3
#define MAX_NR_SERVICE_RECORD_ITEMS 0
#define MAX_NR_AVDTP_STREAM_ENDPOINTS 0
#define MAX_NR_AVDTP_CONNECTIONS 0
#define MAX_NR_AVRCP_CONNECTIONS 0

// Buffer sizes
#define HCI_ACL_PAYLOAD_SIZE 255
#define HCI_INCOMING_PRE_BUFFER_SIZE 6

// Enable various features
#define ENABLE_ATT_DELAYED_RESPONSE
#define ENABLE_GATT_OVER_EATT
#define ENABLE_LE_SECURE_CONNECTIONS
#define ENABLE_MICRO_ECC_FOR_LE_SECURE_CONNECTIONS

// Disable features we don't need
#define ENABLE_CLASSIC 0
#define ENABLE_SDP 0
#define ENABLE_RFCOMM 0

#endif
